apiVersion: v1
kind: Service
metadata:
  name: project-ext-net
  namespace: ims
spec:
 type: NodePort
 selector:
    app: ims-project 
 ports:
 - name: http
   port: 8085
   targetPort: 8085
   nodePort: 30085
