apiVersion: v1
kind: Pod
metadata:
  name: client1
  namespace: ims
spec:
  containers:
  - name: test1
    image: library/busybox
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
