apiVersion: v1
kind: Service
metadata:
  name: mysql-ext-net
  namespace: ims
spec:
 type: NodePort
 selector:
    app: mysql
 ports:
 - name: http
   port: 3306
   targetPort: 3306
   nodePort: 30306
