kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim1
  namespace: ims
spec:
  accessModes:  ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Mi
  storageClassName:  nfs
