apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.es.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - port: {{ .Values.externalService.port }}
      targetPort: {{ .Values.externalService.targetPort }}
      name: http
      nodePort: {{ .Values.externalService.nodePort }}
  selector:
    {{- include "mysql.selector" . | nindent 4 }}
