apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.configMap.name" . }}
  labels:
    app: {{ .Values.configMap.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  master.cnf: |
    {{ tpl (.Files.Get "conf/master.cnf") . | indent 4 | trim }}
  slave.cnf: |
    {{ tpl (.Files.Get "conf/slave.cnf") . | indent 4 | trim }}

{{- range .Values.extraConfigMaps }}
  {{ .subPath }} : {{ .data | quote }}
{{- end }}
