apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ include "mysql.password" . | b64enc | quote }}