apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconf
  namespace: ims
  labels:
    app: mysqlconf
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    default_authentication_plugin = mysql_native_password
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    # super-read-only # ims project not support Read-write separation
    default_authentication_plugin = mysql_native_password
    relay-log = mysql-2-relay-bin